channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.0.5
- lammps =2023.08.02
- mpich
- numpy =1.26.0
- pandas =2.1.1
- pympipool =0.7.1
- pylammpsmpi =0.2.3
- sqsgenerator =0.3
- structuretoolkit =0.0.11
