channels:
- conda-forge
dependencies:
- coverage
- ase =3.22.1
- atomistics =0.1.21
- lammps =2023.11.21=*_mpi_openmpi_*
- numpy =1.26.3
- openmpi
- pandas =2.2.0
- jinja2 =3.1.3
- pympipool =0.7.9
- pylammpsmpi =0.2.11
- sqsgenerator =0.3
- structuretoolkit =0.0.17
