channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.11
- lammps =2023.08.02
- mpich
- numpy =1.26.2
- pandas =2.1.3
- jinja2 =3.1.2
- pympipool =0.7.9
- pylammpsmpi =0.2.9
- sqsgenerator =0.3
- structuretoolkit =0.0.15
