channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.2
- lammps =2023.08.02
- mpich
- numpy =1.26.0
- pandas =2.1.3
- pympipool =0.7.5
- pylammpsmpi =0.2.5
- sqsgenerator =0.3
- structuretoolkit =0.0.11
