channels:
- conda-forge
dependencies:
- ase =3.23.0
- atomistics =0.1.30
- lammps =2024.02.07=*_mpi_mpich_*
- mpich
- numpy =1.26.4
- pandas =2.2.2
- jinja2 =3.1.4
- pympipool =0.8.4
- pylammpsmpi =0.2.19
- sqsgenerator =0.3
- structuretoolkit =0.0.25
