channels:
- conda-forge
dependencies:
- coverage
- ase =3.23.0
- atomistics =0.1.35
- lammps =2024.06.27=*_mpi_openmpi_*
- numpy =1.26.4
- openmpi =4.1.6
- pandas =2.2.2
- jinja2 =3.1.4
- pylammpsmpi =0.2.25
- sqsgenerator =0.3
- structuretoolkit =0.0.28
