channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.21
- lammps =2022.06.23
- numpy =1.26.0
- openmpi
- jinja2 =2.11.3
- pandas =1.5.3
- pympipool =0.7.15
- pylammpsmpi =0.2.14
- sqsgenerator =0.2
- structuretoolkit =0.0.11
