channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.21
- lammps =2023.08.02=*_mpi_mpich_*
- mpich
- numpy =1.26.3
- pandas =2.2.0
- jinja2 =3.1.3
- pympipool =0.7.11
- pylammpsmpi =0.2.11
- sqsgenerator =0.3
- structuretoolkit =0.0.17
