channels:
- conda-forge
dependencies:
- ase =3.23.0
- atomistics =0.1.31
- lammps =2024.02.07=*_mpi_mpich_*
- mpich
- numpy =1.26.4
- pandas =2.2.2
- jinja2 =3.1.4
- executorlib =0.0.1
- pylammpsmpi =0.2.22
- sqsgenerator =0.3
- structuretoolkit =0.0.25
