channels:
- conda-forge
dependencies:
- coverage
- ase =3.22.1
- atomistics =0.1.14
- lammps =2023.08.02
- numpy =1.26.2
- openmpi
- pandas =2.1.4
- jinja2 =3.1.2
- pympipool =0.7.9
- pylammpsmpi =0.2.10
- sqsgenerator =0.3
- structuretoolkit =0.0.15
