channels:
- conda-forge
dependencies:
- coverage
- ase =3.22.1
- atomistics =0.1.24
- lammps =2023.11.21=*_mpi_openmpi_*
- numpy =1.26.4
- openmpi
- pandas =2.2.2
- jinja2 =3.1.3
- pympipool =0.7.17
- pylammpsmpi =0.2.15
- sqsgenerator =0.3
- structuretoolkit =0.0.21
