channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.2
- lammps =2022.06.23
- numpy =1.26.0
- openmpi
- pandas =2.1.3
- pympipool =0.7.2
- pylammpsmpi =0.2.5
- sqsgenerator =0.3
- structuretoolkit =0.0.11
