channels:
- conda-forge
dependencies:
- ase =3.23.0
- atomistics =0.1.32
- lammps =2024.06.27=*_mpi_mpich_*
- mpich =4.2.2
- numpy =2.1.0
- pandas =2.2.2
- jinja2 =3.1.4
- pylammpsmpi =0.2.25
- sqsgenerator =0.3
- structuretoolkit =0.0.28
