channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.0.5
- lammps =2023.03.28
- mpich
- numpy =1.23.5
- pandas =2.1.0
- pympipool =0.7.0
- pylammpsmpi =0.2.3
- sqsgenerator =0.2
- structuretoolkit =0.0.11
