channels:
- conda-forge
dependencies:
- coverage
- coveralls =3.3.1
- ase =3.22.1
- atomistics =0.0.7
- lammps =2023.08.02
- numpy =1.26.0
- openmpi
- pandas =2.1.3
- pympipool =0.7.3
- pylammpsmpi =0.2.5
- sqsgenerator =0.3
- structuretoolkit =0.0.11
