channels:
- conda-forge
dependencies:
- ase =3.22.1
- atomistics =0.1.23
- lammps =2023.11.21=*_mpi_mpich_*
- mpich
- numpy =1.26.4
- pandas =2.2.0
- jinja2 =3.1.3
- pympipool =0.7.15
- pylammpsmpi =0.2.13
- sqsgenerator =0.3
- structuretoolkit =0.0.21
