# This workflow is used to run the unittest of pyiron

name: OpenMPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.11'
          label: osx-64-py-3-11
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment-openmpi.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 5
      run: |
        pip install versioneer[toml]==0.29
        pip install . --no-deps --no-build-isolation
        for f in $(ls tests/*.py); do if [[ "$f" == *"tests/test_"* ]];then echo $f; coverage run --omit="pyiron_lammps/_version.py,tests/*" -m unittest $f; fi; done
    - name: Coveralls
      if:  matrix.label == 'linux-64-py-3-11'
      uses: coverallsapp/github-action@v2
